spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://localhost:3306/universe?useSSL=false&serverTimezone=UTC
    username: root
    password: hsp
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080